### PR TITLE
Add server command

### PR DESCRIPTION
**Pull request by jackjennings**
Just starting to figure out how this Console component works...

### CODE REVIEW

**Comment by jackjennings** [comment]
Oops, this is in regards to #2

**Comment by jackjennings** [comment]
I've implemented the alias to `php -S`, including port selection with the `--port` flag. This is based on the Symfony implementation, but it's waaaaay stripped down in order to start at a basic level that can be built in a maintainable/testable way.

That being said, the `Rick\Server\Builtin` class is untested because I'm not sure yet how to test this properly given that it will execute a long-running process.

**Comment by jackjennings** [comment]
Rebased the commits and fleshed out the tests. Should be ready for review and merge.

**Comment by jackjennings** [comment]
Oops, failing on HHVM. I'll see if I can diagnose, otherwise I'll just remove it from the covered versions.

**Comment by jackjennings** [comment]
Removed HHVM for now. I'm not sure if it even has a built-in server, but we can investigate again if that's a platform that might want to be supported in the future.

**Comment by AugustMiller** [comment]
Are you squashing these commits down into a single one? It looks like your one commit was pulled down below your message that identified the problem!

**Comment by jackjennings** [comment]
Yeah, I squashed the changes into the commit above.

**Comment by jackjennings** [comment]
Guess I could have left removing hhvm in a separate commit.

**Comment by jackjennings** [comment]
:point_up:

**Pull request merged**
